### ISSUE TITLE
Doesn't follow the same convention as GitHub

### ISSUE THREAD

**Issue by captbaritone** [regexhq/regex-username#1]
The docs say this repo uses the same convention that GitHub does and then lists an incomplete description of GitHub's limitations on usernames. The actual limitations are (at least):

> Username may only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen

<img width="464" alt="screen shot 2016-08-15 at 7 38 39 am" src="https://cloud.githubusercontent.com/assets/162735/17667825/72606ab2-62bb-11e6-91b5-082b9eb25992.png">

Might be worth updating the docs.

**Comment by tunnckoCore** [comment]
Yea, thanks. I think for that one `^\w+-?\w+(?!-)$`?

Matches only last two:

```
-foo-bar
foo-bar-
foo--bar
foo-bar // match
foobar // match
```

**Comment by tunnckoCore** [comment]
@jonschlinkert @yoshuawuyts need to publish v2, I don't have rights in npm.

**Comment by jonschlinkert** [comment]
just added you, didn't know I had rights to it

**Comment by tunnckoCore** [comment]
Thanks! Yea, I even don't know for which repos i have rights here, too. :D

**Comment by tunnckoCore** [comment]
@captbaritone, just published `v2` :)

**Comment by captbaritone** [comment]
👏 Thanks!
