### ISSUE TITLE
GitHub doesn't allow an underscore

### ISSUE THREAD

**Issue by sorashi** [regexhq/regex-username#2]
![chrome_2017-09-13_19-52-19](https://user-images.githubusercontent.com/6270283/30392574-88c1b552-98bd-11e7-8d03-e45f7c5472f8.png)

```js
var regex = require("regex-username");
regex().test("hello_world"); // true
```

`\w` is an equivalent to `[a-zA-Z0-9_]`.
`\w` captures `_`, but GitHub doesn't allow it in your username.

**Comment by tunnckoCore** [comment]
It's probably something new, cuz i was trying it back than
